'use client';

import { StyleSheet } from '@react-pdf/renderer';
import { PDF_FONT_FAMILIES } from '@/lib/paths/pdf-fonts';
import {
    PDF_BRAND_COLOR,
    PDF_BRAND_TINT,
    PDF_FRAME_INSET_PT,
    PDF_CONTENT_PADDING_PT,
    PDF_INNER_BACKGROUND,
    PDF_RADIUS_BUTTON_PT,
} from '@/lib/paths/pdf-print-tokens';

export const pdfFontFamilies = PDF_FONT_FAMILIES;

/** @deprecated use PDF_CONTENT_PADDING_PT — kept for chart components */
export const PDF_MARGIN = PDF_CONTENT_PADDING_PT;
export const PDF_HEADER_HEIGHT = 36;
export const PDF_BRAND_PURPLE = '#b638ff';
export const PDF_ACCENT_LIGHT = 'rgba(182, 56, 255, 0.08)';

export const pdfColors = {
    black: '#000000',
    gray900: '#111827',
    gray700: '#374151',
    gray600: '#4B5560',
    gray500: '#6B7280',
    gray400: '#9CA3AF',
    gray200: '#E5E7EB',
    gray100: '#F3F4F6',
    white: '#FFFFFF',
    error: '#DC2626',
    warning: '#D97706',
    notice: '#2563EB',
    success: '#059669',
    brand: PDF_BRAND_COLOR,
    brandTint: PDF_BRAND_TINT,
    innerBg: PDF_INNER_BACKGROUND,
};

export const pdfChapterColors = {
    issues: { main: '#B91C1C', bg: 'rgba(185, 28, 28, 0.08)' },
    summary: { main: PDF_BRAND_PURPLE, bg: PDF_ACCENT_LIGHT },
    visual: { main: '#1D4ED8', bg: 'rgba(29, 78, 216, 0.08)' },
    ux: { main: '#0D9488', bg: 'rgba(13, 148, 136, 0.08)' },
    structure: { main: '#4F46E5', bg: 'rgba(79, 70, 229, 0.08)' },
    seo: { main: '#047857', bg: 'rgba(4, 120, 87, 0.08)' },
    infra: { main: '#C2410C', bg: 'rgba(194, 65, 12, 0.08)' },
    geo: { main: '#0891B2', bg: 'rgba(8, 145, 178, 0.08)' },
    competitors: { main: '#7C3AED', bg: 'rgba(124, 58, 237, 0.08)' },
} as const;

export type PdfChapterKey = keyof typeof pdfChapterColors;

export const pdfStyles = StyleSheet.create({
    page: {
        flexDirection: 'column',
        backgroundColor: pdfColors.innerBg,
        fontFamily: PDF_FONT_FAMILIES.body,
        fontSize: 10,
    },
    coverPage: {
        backgroundColor: PDF_BRAND_COLOR,
    },
    coverAccentBar: {
        position: 'absolute',
        top: PDF_FRAME_INSET_PT,
        left: PDF_FRAME_INSET_PT,
        right: PDF_FRAME_INSET_PT,
        height: 4,
        backgroundColor: pdfColors.brand,
        borderTopLeftRadius: 0,
        borderTopRightRadius: PDF_RADIUS_BUTTON_PT,
    },
    coverLogoWrap: {
        flexDirection: 'row',
        justifyContent: 'flex-start',
        marginBottom: 32,
    },
    coverTitle: {
        fontFamily: PDF_FONT_FAMILIES.headline,
        fontSize: 36,
        fontWeight: 'bold',
        color: pdfColors.gray900,
        marginBottom: 10,
        letterSpacing: -1.2,
        lineHeight: 1.05,
    },
    coverSubtitle: {
        fontFamily: PDF_FONT_FAMILIES.headline,
        fontSize: 9,
        color: pdfColors.gray500,
        textTransform: 'uppercase',
        letterSpacing: 1.4,
        marginBottom: 16,
    },
    coverUrlBox: {
        backgroundColor: pdfColors.white,
        paddingVertical: 14,
        paddingHorizontal: 16,
        borderRadius: PDF_RADIUS_BUTTON_PT / 2,
        marginBottom: 22,
        borderWidth: 2,
        borderColor: pdfColors.brand,
    },
    coverUrl: {
        fontFamily: PDF_FONT_FAMILIES.headline,
        fontSize: 11,
        color: pdfColors.gray900,
        fontWeight: 'bold',
    },
    coverMeta: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        gap: 16,
        marginBottom: 20,
    },
    coverMetaItem: {
        fontSize: 9,
        color: pdfColors.gray500,
    },
    scoreGrid: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        gap: 10,
        marginBottom: 8,
    },
    scoreCard: {
        width: '22%',
        minWidth: 90,
        padding: 12,
        borderRadius: PDF_RADIUS_BUTTON_PT / 2,
        backgroundColor: pdfColors.white,
        borderWidth: 2,
        borderColor: pdfColors.brandTint,
    },
    scoreCardValue: {
        fontFamily: PDF_FONT_FAMILIES.headline,
        fontSize: 18,
        fontWeight: 'bold',
        color: pdfColors.gray900,
        marginBottom: 2,
    },
    scoreCardLabel: {
        fontFamily: PDF_FONT_FAMILIES.headline,
        fontSize: 8,
        color: pdfColors.gray500,
        textTransform: 'uppercase',
        letterSpacing: 0.5,
    },
    header: {
        flexDirection: 'row',
        justifyContent: 'flex-end',
        alignItems: 'center',
        height: PDF_HEADER_HEIGHT,
        marginBottom: 14,
        borderBottomWidth: 1,
        borderBottomColor: pdfColors.gray200,
    },
    footer: {
        position: 'absolute',
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        paddingTop: 8,
        borderTopWidth: 1,
        borderTopColor: pdfColors.gray200,
        fontSize: 8,
        color: pdfColors.gray500,
    },
    sectionTitle: {
        fontFamily: PDF_FONT_FAMILIES.headline,
        fontSize: 12,
        fontWeight: 'bold',
        color: pdfColors.gray900,
        marginTop: 10,
        marginBottom: 6,
        paddingHorizontal: 12,
        paddingVertical: 8,
        borderRadius: PDF_RADIUS_BUTTON_PT / 2,
        borderWidth: 1,
        borderColor: pdfColors.gray200,
    },
    subsectionTitle: {
        fontFamily: PDF_FONT_FAMILIES.headline,
        fontSize: 9,
        fontWeight: 'bold',
        color: pdfColors.gray700,
        marginTop: 6,
        marginBottom: 4,
    },
    bodyText: {
        fontSize: 9,
        color: pdfColors.gray700,
        marginBottom: 4,
        lineHeight: 1.45,
    },
    metaText: {
        fontSize: 9,
        color: pdfColors.gray500,
        marginBottom: 2,
    },
    tableRow: {
        flexDirection: 'row',
        marginBottom: 4,
        fontSize: 9,
    },
    tableLabel: {
        width: 130,
        color: pdfColors.gray500,
    },
    tableValue: {
        flex: 1,
        color: pdfColors.gray700,
    },
    cardBox: {
        backgroundColor: pdfColors.white,
        padding: 12,
        borderRadius: PDF_RADIUS_BUTTON_PT / 2,
        marginBottom: 10,
        borderWidth: 1,
        borderColor: pdfColors.gray200,
    },
    recommendationRow: {
        marginBottom: 10,
        paddingHorizontal: 12,
        paddingVertical: 8,
        borderWidth: 1,
        borderColor: pdfColors.brandTint,
        backgroundColor: pdfColors.brandTint,
        borderRadius: PDF_RADIUS_BUTTON_PT / 2,
    },
    recommendationTitle: {
        fontFamily: PDF_FONT_FAMILIES.headline,
        fontSize: 9,
        fontWeight: 'bold',
        color: pdfColors.gray900,
        marginBottom: 2,
    },
    recommendationDesc: {
        fontSize: 8,
        color: pdfColors.gray600,
        lineHeight: 1.35,
    },
    bulletItem: {
        flexDirection: 'row',
        marginBottom: 4,
        paddingLeft: 8,
    },
    bulletDot: {
        width: 4,
        marginRight: 8,
        marginTop: 5,
        height: 4,
        borderRadius: 2,
        backgroundColor: pdfColors.brand,
    },
    riskPill: {
        paddingHorizontal: 10,
        paddingVertical: 5,
        borderRadius: 999,
        marginRight: 8,
        marginBottom: 6,
        borderWidth: 1,
        borderColor: pdfColors.gray200,
    },
    chapterSpreadLeft: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        position: 'relative',
    },
    chapterSpreadGhost: {
        fontFamily: PDF_FONT_FAMILIES.headline,
        fontSize: 120,
        fontWeight: 'bold',
        letterSpacing: -6,
        opacity: 0.18,
    },
    chapterSpreadAccentRing: {
        position: 'absolute',
        width: 180,
        height: 180,
        borderRadius: 90,
        borderWidth: 3,
        opacity: 0.35,
    },
    chapterSpreadRight: {
        flex: 1,
        justifyContent: 'center',
        paddingRight: 12,
        position: 'relative',
    },
    chapterSpreadEyebrow: {
        fontFamily: PDF_FONT_FAMILIES.headline,
        fontSize: 9,
        textTransform: 'uppercase',
        letterSpacing: 1.6,
        marginBottom: 12,
    },
    chapterSpreadTitle: {
        fontFamily: PDF_FONT_FAMILIES.headline,
        fontSize: 30,
        fontWeight: 'bold',
        color: pdfColors.gray900,
        letterSpacing: -0.8,
        marginBottom: 14,
        lineHeight: 1.12,
    },
    chapterSpreadSubtitle: {
        fontSize: 11,
        color: pdfColors.gray600,
        lineHeight: 1.55,
        maxWidth: 380,
    },
    chapterSpreadFooterLogo: {
        position: 'absolute',
        bottom: 0,
        right: 0,
    },
    leadText: {
        fontSize: 11,
        color: pdfColors.gray700,
        lineHeight: 1.55,
        marginBottom: 14,
    },
    contentPanel: {
        backgroundColor: pdfColors.white,
        borderRadius: PDF_RADIUS_BUTTON_PT / 2,
        padding: 16,
        marginBottom: 14,
        borderWidth: 1,
        borderColor: pdfColors.gray200,
    },
    statGrid: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        gap: 12,
        marginBottom: 14,
    },
    statTile: {
        width: '47%',
        backgroundColor: pdfColors.white,
        borderRadius: PDF_RADIUS_BUTTON_PT / 2,
        padding: 12,
        borderWidth: 2,
        borderColor: pdfColors.brandTint,
    },
    statTileLabel: {
        fontFamily: PDF_FONT_FAMILIES.headline,
        fontSize: 7,
        color: pdfColors.gray500,
        textTransform: 'uppercase',
        letterSpacing: 0.8,
        marginBottom: 4,
    },
    statTileValue: {
        fontFamily: PDF_FONT_FAMILIES.headline,
        fontSize: 16,
        fontWeight: 'bold',
        color: pdfColors.gray900,
    },
    dataTableHeader: {
        flexDirection: 'row',
        borderBottomWidth: 2,
        borderBottomColor: pdfColors.gray200,
        paddingBottom: 6,
        marginBottom: 6,
        marginTop: 4,
    },
    dataTableHeaderCell: {
        fontFamily: PDF_FONT_FAMILIES.headline,
        fontSize: 7,
        fontWeight: 'bold',
        color: pdfColors.gray500,
        textTransform: 'uppercase',
        letterSpacing: 0.6,
    },
    dataTableRow: {
        flexDirection: 'row',
        paddingVertical: 6,
        borderBottomWidth: 1,
        borderBottomColor: pdfColors.gray100,
    },
    chartCard: {
        backgroundColor: pdfColors.white,
        borderRadius: PDF_RADIUS_BUTTON_PT / 2,
        padding: 14,
        marginBottom: 14,
        borderWidth: 2,
        borderColor: pdfColors.brandTint,
    },
    chartTitle: {
        fontFamily: PDF_FONT_FAMILIES.headline,
        fontSize: 10,
        fontWeight: 'bold',
        color: pdfColors.gray900,
        marginBottom: 10,
    },
    chartLegendRow: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        gap: 10,
        marginTop: 8,
    },
    chartLegendItem: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 4,
    },
    chartLegendSwatch: {
        width: 8,
        height: 8,
        borderRadius: 4,
    },
    chartLegendLabel: {
        fontSize: 7,
        color: pdfColors.gray600,
    },
    geoQuestionCard: {
        backgroundColor: pdfColors.white,
        borderRadius: PDF_RADIUS_BUTTON_PT / 2,
        padding: 10,
        marginBottom: 8,
        borderWidth: 2,
        borderColor: pdfChapterColors.geo.main,
    },
    geoQuestionHeaderRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'flex-start',
        gap: 8,
        marginBottom: 4,
    },
    geoQuestionTitle: {
        fontFamily: PDF_FONT_FAMILIES.headline,
        fontSize: 8.5,
        fontWeight: 'bold',
        color: pdfColors.gray900,
        lineHeight: 1.3,
        flex: 1,
        maxWidth: '72%',
    },
    geoQuestionMeta: {
        fontSize: 7,
        color: pdfColors.gray600,
        textAlign: 'right',
        maxWidth: '28%',
        lineHeight: 1.3,
    },
    geoQuestionTablePanel: {
        backgroundColor: pdfColors.white,
        borderRadius: 4,
        borderWidth: 1,
        borderColor: pdfColors.gray200,
        paddingHorizontal: 6,
        paddingVertical: 4,
    },
    geoQuestionSectionLabel: {
        fontFamily: PDF_FONT_FAMILIES.headline,
        fontSize: 6,
        color: pdfColors.gray500,
        textTransform: 'uppercase',
        letterSpacing: 0.6,
        marginBottom: 2,
    },
    geoQuestionTableHeader: {
        flexDirection: 'row',
        borderBottomWidth: 1,
        borderBottomColor: pdfColors.gray200,
        paddingBottom: 2,
        marginBottom: 1,
    },
    geoQuestionTableHeaderCell: {
        fontFamily: PDF_FONT_FAMILIES.headline,
        fontSize: 6,
        fontWeight: 'bold',
        color: pdfColors.gray500,
        textTransform: 'uppercase',
        letterSpacing: 0.4,
    },
    geoQuestionTableRow: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingVertical: 2,
        paddingHorizontal: 2,
    },
    geoQuestionCell: {
        fontSize: 7,
        color: pdfColors.gray700,
    },
});
