/** Deutsche UI-Texte für Quick Check Report (CHECKION PDF/PPTX). */
export const EQC_REPORT_COPY = {
  sectionKpi: 'Kernkennzahlen',
  sectionWorkflow: 'Ablauf',
  sectionDomain: 'Domain & Barrierefreiheit',
  sectionTopIssues: 'Top-Probleme',
  sectionPersona: 'AUDION Persona',
  sectionPersonaTraits: 'Eigenschaften',
  sectionGoals: 'Ziele',
  sectionPainPoints: 'Schmerzpunkte',
  sectionGeoCheck: 'GEO-Wettbewerbsanalyse',
  sectionGeoMetrics: 'GEO-Kennzahlen',
  sectionGeoEeat: 'E-E-A-T',
  sectionGeoQuestions: 'GEO-Fragen (Persona-bezogen)',
  sectionGeoRecommendations: 'GEO-Empfehlungen',
  sectionCitations: 'Zitierungen',
  sectionInsights: 'Einschätzung & Empfehlungen',
  sectionFindings: 'Erkenntnisse',
  sectionRecommendations: 'Handlungsempfehlungen',
  sectionAppendix: 'Anhang — Rohdaten & Schritte',
  appendixSteps: 'Workflow-Schritte (Detail)',
  fazit: 'Fazit',
  links: 'Links',
  colIssue: 'Problem',
  colCount: 'Anzahl',
  colName: 'Name',
  colScore: 'Score',
  colPages: 'Seiten',
  colDomain: 'Domain',
  colQuery: 'Frage',
  colPosition: 'Position',
  colShareOfVoice: 'Sichtbarkeitsanteil',
  kpiShareOfVoice: 'Sichtbarkeitsanteil',
  kpiGeoFitness: 'GEO-Tauglichkeit',
  geoIncompleteTitle: 'GEO nicht vollständig',
  geoIncomplete: 'GEO unvollständig',
  geoComplete: 'GEO abgeschlossen',
  noDomainScan: 'Kein Domain-Scan verfügbar.',
  noPersona: 'Keine Persona verfügbar.',
  unknownError: 'Unbekannter Fehler',
  noRecommendations: 'Keine Empfehlungen',
  insightPrefix: 'Erkenntnis',
  recommendationPrefix: 'Empfehlung',
  goalPrefix: 'Ziel',
  painPrefix: 'Schmerzpunkt',
  pdfCoverEyebrow: 'Quick Check',
  pdfExecutiveLead: 'Kernkennzahlen und Ablauf-Übersicht.',
  pdfDomainSection: 'Domain & Top-Probleme',
  pdfGoalsAndPain: 'Ziele & Schmerzpunkte',
  sectionMarket: 'Markt & Trends',
  sectionMarketFindings: 'Markt-Erkenntnisse',
  marketIncomplete: 'Markt-Research unvollständig',
  marketPartial: 'Markt-Research läuft noch im Hintergrund',
  pdfMarketSection: 'Markt-Überblick aus ECHON-Signalen und Waves.',
} as const;

export const EQC_SEVERITY_LABELS_DE: Record<string, string> = {
  error: 'Kritisch',
  warning: 'Warnung',
  success: 'Positiv',
  info: 'Hinweis',
  neutral: 'Neutral',
};

export function eqcSeverityLabel(severity: string | undefined): string {
  if (!severity) return EQC_SEVERITY_LABELS_DE.info;
  return EQC_SEVERITY_LABELS_DE[severity] ?? severity;
}
